name: CI/CD workflow
run-name: ${{ github.actor }} - GitHub Actions
on: 
  workflow_dispatch:
    inputs:
      steps:
        description: 'Which step to run in the pipeline?'
        required: true
        type: choice
        options:
          - integration
          - all
        default: all
jobs:
  integration:
    name: continuous-integration
    runs-on: ubuntu-latest
    if: ${{ inputs.steps == 'all' || inputs.steps == 'integration' }}
    steps:
        - name: Checkout code repo
          uses: actions/checkout@v4
          
        - name: Setup uv
          run: curl -LsSf https://astral.sh/uv/install.sh | sh
          
        - name: Install dependencies
          run: uv sync --group integration
          
        - name: Run ruff check
          run: uv run ruff check
          
        - name: Run pip-audit
          run: uv run pip-audit --vulnerability-service pypi

        - name: Run PyTest
          run: uv run pytest tests
  deployment:
    name: export-model-to-onnx
    runs-on: ubuntu-latest
    needs: integration
    if: ${{ inputs.steps == 'all' && needs.integration.result == 'success'}}
    steps:
      - name: Checkout code repo
        uses: actions/checkout@v4

      - name: Setup uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Install deployment dependencies
        run: uv sync --group deployment

      - name: Download model artifacts
        run: uv run python main.py --script download

      - name: Export model to ONNX
        run: uv run python main.py --script export

      - name: Build Docker image for ONNX inference
        run: docker build -t polish-sentiment-app-onnx:latest .

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token:     ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region:            ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: true

      - name: Build, Tag & Push image
        run: |
          docker build -t polish-sentiment-app-onnx:latest .
          IMAGE_URI=${{ steps.login-ecr.outputs.registry }}/my-ecr-repo:${{ github.sha }}
          docker tag polish-sentiment-app-onnx:latest $IMAGE_URI
          docker push $IMAGE_URI